dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"
cache:
  directories:
    - node_modules
script:
  - "npm test"
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script:
        - npx semantic-release
branches:
  only:
    - master
