dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
  - "6"
  - "4"
cache:
  directories:
    - node_modules
script:
  - "npm run lint"
  - "npm test"
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: skip
      after_success:
        - TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release
branches:
  only:
    - master
